name: Production

on:
  push:
    branches: [
      "master",
    ]

permissions:
  contents: read

jobs:
  production:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd ./mytv-angular
          npm install -g @angular/cli@16.2.2
          npm install
          ng build --configuration production
          cd ../

      - name: rsync deployment
        env:
          dest: '/var/www/my-smart-tv.moukafih.nl'
        run: |
          echo "::group::Prepare Certificate"
          echo "${{secrets.OPENSSH_KEY}}" > id_ed25519
          chmod 600 ./id_ed25519

          echo "::group::Deploy"
          rsync -avz --delete --rsync-path="sudo rsync" -e 'ssh -i ./id_ed25519 -o StrictHostKeyChecking=no' --exclude /id_ed25519 --exclude /.git/ --exclude /.github/ ./mytv-angular/dist/mytv-angular/ ${{vars.SSH_USER}}@${{vars.SSH_HOST}}:${{env.dest}}